#!/bin/bash

if [[ -d ./jdk17 ]]
then
  rm -rf ./jdk17
fi

echo Downloading java...
mkdir "jdk17"
curl -s -L "https://corretto.aws/downloads/resources/17.0.7.7.1/amazon-corretto-17.0.7.7.1-@os@-@arch@.tar.gz" | tar -vxz -C jdk17 --strip-components=1
